# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TfCTools
                                 A QGIS plugin
 A suite of Transport for Cairo tools: RouteLab to SDI migration, GIS2GTFS, and Vehicle & Passenger Flow.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-28
        copyright            : (C) 2025 by Transport for Cairo
        email                : info@transportforcairo.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Transport for Cairo'
__date__ = '2025-08-28'
__copyright__ = '(C) 2025 by Transport for Cairo'


from .tfc_tools_common import ensure_bootstrap
ensure_bootstrap()


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TfCTools class from file TfCTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tfc_tools import TfCToolsPlugin
    return TfCToolsPlugin()
