# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RL2SDI
                                 A QGIS plugin
 This plugin migrates RouteLab data to SDI schema
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-29
        copyright            : (C) 2025 by Transport for Cairo
        email                : info@transportforcairo.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Transport for Cairo'
__date__ = '2025-06-29'
__copyright__ = '(C) 2025 by Transport for Cairo'

# Unified deps handled at plugin root
from ..tfc_tools_common import ensure_bootstrap
ensure_bootstrap()
 

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RL2SDI class from file RL2SDI.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rl2sdi import RL2SDIPlugin
    return RL2SDIPlugin()
