# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VehiclePassengerFlow
                                 A QGIS plugin
 this plugin estimates the vehicle and passenger flow
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-13
        copyright            : (C) 2025 by Transport for Cairo
        email                : info@transportforcairo.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Transport for Cairo'
__date__ = '2025-07-13'
__copyright__ = '(C) 2025 by Transport for Cairo'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VehiclePassengerFlow class from file VehiclePassengerFlow.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .vehicle_passenger_flow import VehiclePassengerFlowPlugin
    return VehiclePassengerFlowPlugin(iface)
