# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GIS2GTFS
                                 A QGIS plugin
 This plugin turns GIS files to GTFS feed
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-02
        copyright            : (C) 2025 by Transport for Cairo
        email                : info@transportforcairo.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Transport for Cairo'
__date__ = '2025-07-02'
__copyright__ = '(C) 2025 by Transport for Cairo'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GIS2GTFS class from file GIS2GTFS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gis2gtfs import GIS2GTFSPlugin
    return GIS2GTFSPlugin(iface) # WE ADDED THE VALUE BETWEEN BRACKETS + MODIFIED gis2gtfs.py TO AVOID THE QGIS ERROR " Python error : Couldn't load plugin 'gis2gtfs' due to an error when calling its classFactory()"
